name: dartway_core_serverpod_flutter
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  serverpod_client: ^2.9.1

  dartway_flutter:
    git: 
      url: https://github.com/dartway/dartway_flutter.git
      ref: master

  
  dartway_core_serverpod_client:
    git:
      url: https://github.com/dartway/dartway_core_serverpod.git
      ref: master
      path: dartway_core_serverpod_client

  dartway_core_serverpod_shared:
    git:
      url: https://github.com/dartway/dartway_core_serverpod.git
      ref: master
      path: dartway_core_serverpod_shared

  collection: ^1.19.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.1

  heif_converter: '>=1.0.0 <2.0.0'
  image: '>=4.1.4 <5.0.0'
  image_picker: '>=1.0.4 <2.0.0'
  intl: '>=0.19.0 <1.0.0'
  path: '>=1.9.0 <2.0.0'
  path_provider: '>=2.1.3 <3.0.0'
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  riverpod_generator: ^2.3.4
  freezed: ^2.4.6
  build_runner: ^2.4.8

dependency_overrides:
  dartway_core_serverpod_client:
    path: ../dartway_core_serverpod_client
  dartway_core_serverpod_shared:
    path: ../dartway_core_serverpod_shared
  # dartway_flutter:
  #   path: ../../dartway_flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
